INSERT INTO curso (nombre) VALUES ('Introducción a la Logística');
INSERT INTO curso (nombre) VALUES ('Administración de Bodegas e Inventarios I');
INSERT INTO curso (nombre) VALUES ('Administración de Transporte');
INSERT INTO curso (nombre) VALUES ('Administración de Bodegas e Inventarios II');
INSERT INTO curso (nombre) VALUES ('Infraestructura de Almacenes');
INSERT INTO curso (nombre) VALUES ('Matemática');
INSERT INTO curso (nombre) VALUES ('Costos Logísticos');
INSERT INTO curso (nombre) VALUES ('Estadística');
INSERT INTO curso (nombre) VALUES ('Planificación de la Producción y de Servicios');
INSERT INTO curso (nombre) VALUES ('Comunicación');
INSERT INTO curso (nombre) VALUES ('Administración de Abastecimiento y Compras');
INSERT INTO curso (nombre) VALUES ('Inventarios y Modelos de Pronósticos');
INSERT INTO curso (nombre) VALUES ('Proyecto de Graduación');
